---
title: "data_analysis"
author: "Qetsiyah Wang"
date: "11/25/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE,
                      fig.height = 6, fig.width = 8)

library(tidyverse)
library(dplyr)
library(plotly)
```


# Tidy Dataset
```{r}

raw_eathealth = read.csv("ehresp_2014.csv") %>%
  mutate(
    tucaseid = as.factor(tucaseid)
  ) %>%
  select(tucaseid, starts_with(c("er", "eu")), -erhhch)

```

## A. Descriptive Statistics
```{r}

desc_eathealth = raw_eathealth %>%
  select(erbmi, euwgt, euhgt, erincome) %>%
  filter_all(all_vars(. > 0)) %>%
  mutate(
    erincome = factor(erincome, labels = c("Income > 185% of poverty threhold", "Income <= 185% of poverty threshold",
                                           "130% < Income < 185% of poverty threshold",
                                           "Income > 130% of poverty threshold", "Income <= 130% of poverty threshold"))
  )

desc_eathealth %>% 
  ggplot(aes(x = erincome, y = erbmi)) + 
  geom_violin(aes(fill = erincome), alpha = .5)

```

## B. External and Internal Indicators that affects the eating health
```{r}

external_indicators = raw_eathealth %>%
  select(erbmi, eugenhth, erincome, eustores) %>%
  filter_all(all_vars(. > 0)) %>%
  rename("physical_health" = "eugenhth") %>%
  mutate(
    physical_health = factor(physical_health, labels = c("Excellent", "Very Good", "Good", "Fair", "Poor")),
     erincome = factor(erincome, labels = c("Income > 185% of poverty threhold", "Income <= 185% of poverty threshold",
                                           "130% < Income < 185% of poverty threshold",
                                           "Income > 130% of poverty threshold", "Income <= 130% of poverty threshold")),
    eustores = factor(eustores, labels = c("Grocery Store", "Supercenter", "Warehouse Club", 
                                           "Drugstore or Convenience Store", "Some Other Place"))
  )

internal_indicators = raw_eathealth %>%
  select(erbmi, eufastfdfrq, euexfreq) %>%
  filter_all(all_vars(. > 0))

```

### Multiple Regression Models

```{r}
mlr_model = lm(internal_indicators$erbmi ~ internal_indicators$eufastfdfrq)
mlr_plot_check = plot_ly(internal_indicators, y = ~ erbmi)

mlr_plot_check = mlr_plot_check %>%
  add_trace(x = ~ eufastfdfrq,  name = "fast_food",
          marker = list(size = 5, color = "rgba(135, 206, 235, 0.9)")) %>%
  add_lines(x = ~ eufastfdfrq, y = fitted(mlr_model))

mlr_plot_check = mlr_plot_check %>%
  add_trace(x = ~ euexfreq, name = "exercise", marker = list(size = 5, color = "rgba(255, 182, 193, 0.8)"))

mlr_plot_check

```

## C. Hypothesis Testing between eating
```{r}

prim_sec_eat = raw_eathealth %>%
  select(erbmi, ertpreat, ertseat) %>%
  filter_all(all_vars(. > 0))


```





